theme="modern"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
format = "{max}°"
chip = "*-isa-*"

# [[block]]
# block = "backlight"

[[block]]
block = "sound"

# [[block]]
# block = "battery"
# format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%F %R"

